### ISSUE TITLE
Provide conda package for python-cdo on Windows

### ISSUE THREAD

**Issue by andreas-h** [conda-forge/python-cdo-feedstock#9]
Even though there are no conda packages for CDO at the moment (see #1), the python-cdo should work on Windows if there is a `cdo.exe` installed.  `cdo.exe` can be downloaded from https://code.mpimet.mpg.de/projects/cdo/files.  So I believe it would be great to have a python-cdo conda package on windows, which does not have cdo as dependency.  What do you think?

**Comment by ocefpaf** [comment]
That may be possible if `python-cdo` does not look for the `cdo` binary during the installation. I'll try that..

However, I am closing this as a duplicated of #1, let's keep the discussion there.
